import React from 'react';
import Head from 'next/head';
import Navbar from './components/navbar';
import Image from 'next/image';


const services = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <div className="container">
                    <div className="row-services">
                        <div className="col-3">
                            <div className='right-services'>
                                <div>
                                    <h1>Services</h1>
                                </div>

                                <ul>
                                    <li>
                                        <Image className='logo-conseption-web' src="/web-design.jpeg" width={130} height={130} alt={''} />
                                    </li>
                                    <li>
                                        <Image className='logo-conseption-web' src="/GST JOS 462-19.jpg" width={130} height={130} alt={''} />
                                    </li>
                                    <li>
                                        <Image className='logo-conseption-web' src="/Responsive.gif" width={130} height={130} alt={''} />
                                    </li>
                                </ul>
                            </div>
                            <div className="col-3">
                                <div className='left-services'>
                                    <ul>
                                        <li>
                                            <h3>Web-Design</h3>
                                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt cumque totam optio aliquam eaque nihil? Qui excepturi tempora eligendi enim. Expedita laboriosam laborum tenetur nihil nesciunt vero deserunt porro sed.</p>
                                        </li>
                                        <li>
                                            <h3>Refonte de site web</h3>
                                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt cumque totam optio aliquam eaque nihil? Qui excepturi tempora eligendi enim. Expedita laboriosam laborum tenetur nihil nesciunt vero deserunt porro sed.</p>
                                        </li>
                                        <li>
                                            <h3>Responsive</h3>
                                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt cumque totam optio aliquam eaque nihil? Qui excepturi tempora eligendi enim. Expedita laboriosam laborum tenetur nihil nesciunt vero deserunt porro sed.</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

            </main>


           


            <footer>
                <div className="footer">
                    <div className="container">
                        <div className="row">
                            <div className="col-2">
                                <div className="footer-col-1">
                                    <h3>Téléchargez notre application</h3>
                                    <p>Téléchargez notre application pour Android et iOS</p>
                                    <div className="app-logo">
                                        <Image className='logo-about' src="/play-store.png" width={130} height={40} alt={''} />
                                        <Image className='logo-about' src="/app-store.png" width={130} height={40} alt={''} />

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    );
};

export default services;