/* eslint-disable react/no-unescaped-entities */
import React from 'react';
import Head from 'next/head';
import Navbar from './components/navbar';
import Image from 'next/image';


const services = () => {
    return (
        <>
            <Head>
                <title>YANIS HARRAT</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <div className="container">
                    <div className="row-services">
                        <div className="col-3">
                            <div className='right-services'>
                                <div>
                                    <h1>Services</h1>
                                </div>

                                <ul>
                                    <li>
                                        <Image className='logo-conseption-web' src="/web-design.jpeg" width={130} height={130} alt={''} />
                                    </li>
                                    <li>
                                        <Image className='logo-conseption-web' src="/GST JOS 462-19.jpg" width={130} height={130} alt={''} />
                                    </li>
                                    <li>
                                        <Image className='logo-conseption-web' src="/Responsive.gif" width={130} height={130} alt={''} />
                                    </li>
                                </ul>
                            </div>
                            <div className="col-3">
                                <div className='left-services'>
                                    <ul>
                                        <li>
                                            <h3>Web-Design</h3>
                                            <p>En tant que web designer, je propose des services de création de sites web professionnels, esthétiques et fonctionnels. Je m'occupe de la navigation, de l'architecture du site, de l'optimisation pour mobile et SEO, ainsi que de la maintenance et mise à jour régulière.</p>
                                        </li>
                                        <li>
                                            <h3>Refonte de site web</h3>
                                            <p>En tant que web designer spécialisé en refonte de site web, je propose des services pour améliorer l'apparence, l'expérience utilisateur, la fonctionnalité et la performance d'un site existant, avec mise à jour de la mise en page, de la navigation, des images et des contenus, ainsi que l'optimisation pour les appareils mobiles et les moteurs de recherche.</p>
                                        </li>
                                        <li>
                                            <h3>Responsive</h3>
                                            <p>En tant que web designer spécialisé en responsive design, je crée des designs adaptatifs pour tous les appareils, et je m'occupe de l'optimisation SEO, de la maintenance et mise à jour des sites web.</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

            </main>


           


            <footer>
                <div className="footer">
                    <div className="container">
                        <div className="row">
                            <div className="col-2">
                                <div className="footer-col-1">
                                    <h3>Téléchargez notre application</h3>
                                    <p>Téléchargez notre application pour Android et iOS</p>
                                    <div className="app-logo">
                                        <Image className='logo-about' src="/play-store.png" width={130} height={40} alt={''} />
                                        <Image className='logo-about' src="/app-store.png" width={130} height={40} alt={''} />

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    );
};

export default services;