import React from 'react';
import Head from 'next/head';
import Navbar from './components/navbar';
import Image from 'next/image';
import Footer from './components/footer';
import Link from 'next/link';

const portfolio = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <div className="portfolio-container">
                    <div className="portfolio-header">
                        <h1>PORTFOLIO</h1>
                        <p>Découvrez mon portfolio, où je vous invite à parcourir mes réalisations passées et en cours, mettant en avant
                        mes compétences en développement web et en design d'interface utilisateur
                        </p>
                    </div>
                    <div className="portfolio-grid">
                        <div className="grid">
                            <div className="grid__item">
                                <div className="card">
                                    <Image className='logo-conseption-web' src="/web-design.jpeg" width={130} height={130} alt={''} />
                                    <div className="card__inner">
                                        <h3 className="card__title">Code Campe</h3>
                                        <p className="category">J'ai conçu et développé une API et un site web pour gérer les emplois d'étudiants dans une école en utilisant des technologies modernes pour une expérience utilisateur intuitive et efficace.</p>
                                    </div>
                                    <div className="card__overlay">
                                    <Link href="#">+</Link>
                                    </div>
                                </div>
                            </div>
                            <div className="grid__item">
                                <div className="card">
                                    <Image className='logo-conseption-web' src="/Logo.png" width={130} height={130} alt={''} />
                                    <div className="card__inner">
                                        <h3 className="card__title">Turbohéberge</h3>
                                        <p className="category">J'ai conçu et développé une API et un site web e-commerce pour vendre des services d'hébergement web en utilisant des technologies modernes pour une expérience utilisateur fluide.</p>
                                    </div>
                                    <div className="card__overlay">
                                    <Link href="#">+</Link>
                                    </div>
                                </div>
                            </div>
                            <div className="grid__item">
                                <div className="card">
                                    <Image className='logo-conseption-web' src="/web-design.jpeg" width={130} height={130} alt={''} />
                                    <div className="card__inner">
                                        <h3 className="card__title">Code-tech</h3>
                                        <p className="category">J'ai conçu et développé un site web e-commerce pour vendre mes services de développement full-stack et de maintenance informatique et électronique. <br /></p>
                                    </div>
                                    <div className="card__overlay">
                                    <Link href="#">+</Link>
                                    </div>
                                </div>
                            </div>
                            <div className="grid__item">
                                <div className="card">
                                    <Image className='logo-conseption-web' src="/web-design.jpeg" width={130} height={130} alt={''} />
                                    <div className="card__inner">
                                        <h3 className="card__title">Portfolio</h3>
                                        <p className="category"> J'ai conçu un portfolio pour montrer mes compétences en développement web, utilisant des technologies modernes pour une expérience utilisateur interactive et agréable..</p>
                                    </div>
                                    <div className="card__overlay">
                                         <Link href="#">+</Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </main>

            <Footer />
        </>
    );
};

export default portfolio;